### ISSUE TITLE
Progressbar is not behaving well with video.js v5

### ISSUE THREAD

**Issue by jothikannan** [cladera/videojs-offset#10]
when we use this Offset plugin the progressbar width is increasing automatically when the video is playing, refer the attached image 

![offset](https://cloud.githubusercontent.com/assets/4100047/11180306/b0767b24-8c7f-11e5-9f81-3893631f4807.png)

**Comment by sveinburne** [comment]
The following css did the trick for me : 

``` css
.vjs-load-progress {
  overflow-x:hidden;
}
```
